/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedMerchantIdRouteImport } from './routes/_authenticated/merchant.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/_authenticated/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMerchantIdRoute = AuthenticatedMerchantIdRouteImport.update({
  id: '/_authenticated/merchant/$id',
  path: '/merchant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/new': typeof AuthenticatedNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/merchant/$id': typeof AuthenticatedMerchantIdRoute
}
export interface FileRoutesByTo {
  '/new': typeof AuthenticatedNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/merchant/$id': typeof AuthenticatedMerchantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/merchant/$id': typeof AuthenticatedMerchantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/new' | '/' | '/merchant/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/new' | '/' | '/merchant/$id'
  id:
    | '__root__'
    | '/_authenticated/new'
    | '/_authenticated/'
    | '/_authenticated/merchant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMerchantIdRoute: typeof AuthenticatedMerchantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/merchant/$id': {
      id: '/_authenticated/merchant/$id'
      path: '/merchant/$id'
      fullPath: '/merchant/$id'
      preLoaderRoute: typeof AuthenticatedMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMerchantIdRoute: AuthenticatedMerchantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
